---
title: "Assignment 02"
author: "Scott Stoltzman"
date: "5/12/2019"
output: html_document
---

### Answer the problems below in the spaces between `<ANSWER BELOW>` and `<ANSWER ABOVE>`

## Practice

1.  Why does this code not work?

    ```{r, error = TRUE}
    my_variable <- 10
    my_varıable
    ```
    
    Look carefully! (This may seem like an exercise in pointlessness, but
    training your brain to notice even the tiniest difference will pay off
    when programming.)
    
    
    `<ANSWER BELOW>`
The code above appears to work.  It appears to be assigning "my_variable" a value of 10.  When "my_variable" is called in, you get the value of 10.

So I don't understand what is wrong with it.

In order to double check it, I changed the code to error = FALSE (which should cause knitting to fail... and it still worked)


*REVISED ANSWER*

my_varıable - the i in variable is missing the dot.  no flipping clue what that character is... but I am also equally confused as to why it still delivered the answer of 10.  But that is the final answer.

    `<ANSWER ABOVE>`
    
    
1.  Press Alt + Shift + K. What happens? How can you get to the same place
    using the menus?


    `<ANSWER BELOW>`
The Keyboard Shortcut Quick Reference shows up.  You can also go to *Tools* and select *Keyboard Shortcuts Help*
    `<ANSWER ABOVE>`



#### Bonus - what happens if you hit "knit"?

    `<ANSWER BELOW>`
I am assuming you mean that we go to *File* and click *Knit Document*... which can also be accomplished by pressing *Ctrl + Shift + K*...

On line 5, the output is a HTML Document.  So by knitting it, does it execute it the code as an HTML document?
    `<ANSWER ABOVE>`

#### Remember to commit your changes and push to your repository
